#!/bin/bash
# script to take user parameter input and scan documents

# function for user parameter selection
# $1 is param name | $@ is param array
param_select () {
  local param_name="$1"
  shift
  local param_array=("$@")
  local param_bool=false
  local user_select
  printf "Which $param_name? (${param_array[*]})%b\n"
  while [ $param_bool = false ] ; do
    read user_select
    if [[ " ${param_array[@]} " =~ " $user_select " ]] ; then
      param_bool=true
      printf "$user_select selected%b\n\n"
    elif [ -z "$user_select" ] ; then
      param_bool=true
      user_select="${param_array[0]}"
      printf "$user_select selected%b\n\n"
    else
      printf "Invalid format %b\n"
    fi
  done
  eval "$param_name"_scan="$user_select"
}

printf "Scan parameters required (leave blank for 1st param):%b\n\n"

# user selects the format
name=format
array=(".pnm" ".tiff" ".png" ".jpeg")
param_select $name ${array[*]}

# user selects the mode
name=mode
array=("gray" "color")
param_select $name ${array[*]}

# user selects the resolution
name=resolution
array=("75" "100" "200" "300" "600" "1200")
param_select $name ${array[*]}

#user selects the source
name=source
array=("Flatbed" "ADF")
param_select $name ${array[*]}

# user defines the path to save scan
printf "Where to save?%b\n"
dest_bool=false
while [ $dest_bool = false ] ; do
  read -e dest_scan
  eval dest_scan=$dest_scan
  if [ ! -z "$dest_scan" ] ; then
    dest_bool=true
    printf "Saving to $dest_scan$format_scan%b\n\n"
  elif [ -z "$dest_scan" ] ; then
    printf "Must define save path%b\n"
  fi
done

# run scanimage with user defined parameters
scanimage -v -d escl:http://192.168.1.138:8080 --format="${format_scan:1}" --mode "$mode_scan" --resolution "$resolution_scan" --source "$source_scan" > "$dest_scan$format_scan"

# scan success confirmation
if [ -f "$dest_scan$format_scan" ] ; then
  printf "%b\nScan success!%b\n"
else
  printf "Something went wrong!%b\n"
fi